name: 🐳Build🐋

on: 
  push: 
    branches:
      - 'main'
  workflow_dispatch: ~

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - 
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - 
        name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with: 
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
      - 
        name: "Build and push"
        uses: docker/build-push-action@v6
        with: 
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: |
              ghcr.io/alex2702/docker-fivefilters-full-text-rss:latest
              ghcr.io/alex2702/docker-fivefilters-full-text-rss:3.8.2
